services:
  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:6 # renovate: datasource=docker
    container_name: forgejo_runner
    restart: unless-stopped
    command: forgejo-runner daemon --config /data/config.yml
    working_dir: /data
    volumes:
      - ./data:/data
      - ./data/config.yml:/data/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - forgejo-internal
      - traefik
    group_add:
      - "988"
    extra_hosts:
      - "git.yourdomain.com:<forgejo-host-ip>"
      - "homelab-server:<forgejo-host-ip>"
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "1.0"
        reservations:
          memory: 128m

networks:
  forgejo-internal:
    external: true
    name: forgejo_forgejo-internal
  traefik:
    external: true
