services:
  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:6 # renovate: datasource=docker
    container_name: forgejo_runner
    restart: unless-stopped
    command: forgejo-runner daemon
    working_dir: /data
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - forgejo-internal
    group_add:
      - "988"
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "1.0"
        reservations:
          memory: 128m

networks:
  forgejo-internal:
    external: true
    name: forgejo_forgejo-internal
