services:
  guacd:
    container_name: guacamole_guacd
    image: guacamole/guacd:1.6.0
    restart: unless-stopped
    networks:
      - guac-internal
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  guacamole-db:
    container_name: guacamole_db
    image: postgres:14.21
    restart: unless-stopped
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: ${GUAC_DB_PASS}
    volumes:
      - ./guac-db-data:/var/lib/postgresql/data
    networks:
      - guac-internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guacamole_user -d guacamole_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  guacamole:
    container_name: guacamole_app
    image: guacamole/guacamole:1.6.0
    restart: unless-stopped
    depends_on:
      guacamole-db:
        condition: service_healthy
      guacd:
        condition: service_started
    environment:
      GUACD_HOSTNAME: guacd
      # Nombres de variables actualizados para evitar el error de conexión
      POSTGRESQL_HOSTNAME: guacamole-db
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USERNAME: guacamole_user
      POSTGRESQL_PASSWORD: ${GUAC_DB_PASS}
    networks:
      - guac-internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${GUAC_ROUTER_NAME}.rule=Host(`${GUACAMOLE_DOMAIN}`)"
      - "traefik.http.routers.${GUAC_ROUTER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${GUAC_ROUTER_NAME}.tls=true"
      - "traefik.http.routers.${GUAC_ROUTER_NAME}.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"
      - "traefik.http.routers.${GUAC_ROUTER_NAME}.middlewares=authelia-auth@file,guac-root-redirect"
      - "traefik.http.middlewares.guac-root-redirect.redirectregex.regex=^https?://([^/]+)/?$$"
      - "traefik.http.middlewares.guac-root-redirect.redirectregex.replacement=https://$$1/guacamole/"
      - "traefik.http.services.${GUAC_ROUTER_NAME}-svc.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  guac-internal:
  traefik:
    external: true
