services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.6 # renovate: datasource=docker
    container_name: crowdsec
    restart: unless-stopped
    env_file:
      - .env
    environment:
      GID: "${GID:-1000}"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik crowdsecurity/sshd crowdsecurity/iptables crowdsecurity/nextcloud crowdsecurity/http-cve LePresidente/authelia LePresidente/jellyfin gauth-fr/immich crowdsecurity/appsec-crs-exclusion-plugin-nextcloud"
    volumes:
      - ${DATA_DIR}/:/etc/crowdsec/
      - ${LOGS_DIR}/traefik:/var/log/traefik:ro
      - ${LOGS_DIR}/authelia:/var/log/authelia:ro
      # - ${LOGS_DIR}/immich:/var/log/immich:ro          # uncomment when immich is up
      # - ${LOGS_DIR}/n8n:/var/log/n8n:ro                # uncomment when n8n is up
      # - /home/note/docker/data/nextcloud/logs/nextcloud.log:/var/log/nextcloud/nextcloud.log:ro        # uncomment when nextcloud is up
      # - /home/note/docker/data/newm/logs/nextcloud.log:/var/log/nextcloud-newm/nextcloud.log:ro       # uncomment when newm is up
      - /var/log/auth.log:/var/log/auth.log:ro
      - crowdsec-db:/var/lib/crowdsec/data/
    networks:
      - traefik
    ports:
      - "8082:8080"
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.50"
        reservations:
          memory: 256m

  crowdsec-bouncer:
    image: ghcr.io/thespad/traefik-crowdsec-bouncer:latest # renovate: datasource=docker
    container_name: bouncer-traefik
    restart: unless-stopped
    environment:
      CROWDSEC_BOUNCER_API_KEY: ${CROWDSEC_BOUNCER_API_KEY}
      CROWDSEC_AGENT_HOST: crowdsec:8080
      GIN_MODE: release
    networks:
      - traefik
    depends_on:
      - crowdsec
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 64m
          cpus: "0.10"
        reservations:
          memory: 32m

volumes:
  crowdsec-db:

networks:
  traefik:
    external: true
