services:
  beets:
    image: lscr.io/linuxserver/beets:2.8.0 # renovate: datasource=docker
    container_name: beets
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/data:/config
      - ${DATA_DIR}/downloads:/downloads
      - ${DATA_DIR}/music:/music
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Madrid}
    networks:
      - media
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.50"
        reservations:
          memory: 64m

networks:
  media:
    external: true
