services:
  watchtower:
    container_name: watchtower
    #image: containrrr/watchtower:latest
    image: ghcr.io/nicholas-fedor/watchtower:1.14.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - WATCHTOWER_LIFECYCLE_HOOKS=1
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      # - WATCHTOWER_NOTIFICATION_URL=telegram://${BOT_TOKEN}@telegram/?channels=${CHAT_ID}
      - WATCHTOWER_NOTIFICATION_URL=ntfy://${NTFY_USER}:${NTFY_PASSWORD}@ntfy.yourdomain.com/alerts-watchtower
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME="${MACHINE}"
    command: --schedule "0 0 4 * * *" --cleanup --label-enable
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    # deploy:
    #   resources:
    #     limits:
    #       memory: 100MB
    #     reservations:
    #       memory: 50MB
