services:
  watchtower:
    image: ghcr.io/nicholas-fedor/watchtower:1.15.0 # renovate: datasource=docker
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=${TZ}
      - WATCHTOWER_LIFECYCLE_HOOKS=1
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=ntfy://${NTFY_USER}:${NTFY_PASSWORD}@ntfy.yourdomain.com/alerts-watchtower
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=${MACHINE}
    command: --schedule "0 0 4 * * *" --cleanup --label-enable
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 100m
          cpus: "0.25"
        reservations:
          memory: 50m
