name: Security Scan (Trivy)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 4 * * 0' # Runs every Sunday at 4:00 AM

jobs:
  scan-secrets-and-iac:
    name: Scan Secrets and Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Trivy vulnerability & secret scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0 safe
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          scanners: 'vuln,secret,misconfig'
          severity: 'CRITICAL,HIGH'
