services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:v4.0.0-ls219
    container_name: ddclient
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./config:/config
    restart: unless-stopped
    networks:
      - ddclient_ntwrk
    healthcheck:
      test: ["CMD-SHELL", "pgrep ddclient || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  ddclient_ntwrk:
    name: ddclient_ntwrk
