services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:v4.0.0-ls219
    container_name: ddclient
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
    volumes:
      - ./config:/config
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - ddclient_ntwrk
    healthcheck:
      test: ["CMD-SHELL", "pgrep ddclient || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    # deploy:
    #   resources:
    #     limits:
    #       memory: 50M
    #     reservations:
    #       memory: 25M

networks:
  ddclient_ntwrk:
    name: ddclient_ntwrk
